version: '3.4'
services:
  kas_postgres:
    container_name: kas-db
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'