package tk.aizydorczyk.kashubian.domain.model.entity.variation

data class StandardAllKindVariation(
        val nominativeMasculine: String? = null,
        val nominativeFeminine: String? = null,
        val nominativeNeuter: String? = null,
        val genitiveMasculine: String? = null,
        val genitiveFeminine: String? = null,
        val genitiveNeuter: String? = null,
        val dativeMasculine: String? = null,
        val dativeFeminine: String? = null,
        val dativeNeuter: String? = null,
        val accusativeMasculine: String? = null,
        val accusativeFeminine: String? = null,
        val accusativeNeuter: String? = null,
        val instrumentalMasculine: String? = null,
        val instrumentalFeminine: String? = null,
        val instrumentalNeuter: String? = null,
        val locativeMasculine: String? = null,
        val locativeFeminine: String? = null,
        val locativeNeuter: String? = null,
        val vocativeMasculine: String? = null,
        val vocativeFeminine: String? = null,
        val vocativeNeuter: String? = null,
        val nominativePluralMasculineKind: String? = null,
        val nominativePluralNonMasculine: String? = null,
        val genitivePluralMasculineKind: String? = null,
        val genitivePluralNonMasculine: String? = null,
        val dativePluralMasculineKind: String? = null,
        val dativePluralNonMasculine: String? = null,
        val accusativePluralMasculineKind: String? = null,
        val accusativePluralNonMasculine: String? = null,
        val instrumentalPluralMasculineKind: String? = null,
        val instrumentalPluralNonMasculine: String? = null,
        val locativePluralMasculineKind: String? = null,
        val locativePluralNonMasculine: String? = null,
        val vocativePluralMasculineKind: String? = null,
        val vocativePluralNonMasculine: String? = null
)