package tk.aizydorczyk.kashubian.domain.model.entity.variation

data class VerbVariation(
        val ternyTense: VerbVariationFirst = VerbVariationFirst(),
        val uszliTense: VerbVariationThird = VerbVariationThird(),
        val archajiznowiUszliTense: VerbVariationThird = VerbVariationThird(),
        val opisoweFormeTernyTense: VerbVariationSecond = VerbVariationSecond(),
        val konstrukcjeUszliTense: VerbVariationThird = VerbVariationThird(),
        val zauszliTenseFirst: VerbVariationThird = VerbVariationThird(),
        val zauszliTenseSecond: VerbVariationThird = VerbVariationThird(),
        val zauszliTenseThird: VerbVariationThird = VerbVariationThird(),
        val zauszliTenseImpersonal: String? = null,
        val przindnyProstTense: VerbVariationSecond = VerbVariationSecond(),
        val przindnyZasadzonyTenseFirst: VerbVariationThird = VerbVariationThird(),
        val przindnyZasadzonyTenseSecond: VerbVariationThird = VerbVariationThird(),
        val imperativeMode: VerbVariationFirst = VerbVariationFirst(),
        val conditionalMode: VerbVariationThird = VerbVariationThird(),
        val conditionalModeImpersonal: String? = null,
        val infinitive: String? = null,
        val aspectEquivalent: String? = null,
        val contemporaryAdverbialParticiple: String? = null,
        val priorAdverbialParticiple: String? = null,
        val gerundium: String? = null,
        val grammaticalKind: String? = null,
        val gerundiumVariation: StandardVariation = StandardVariation(),
        val activeAdjectivalParticiple: String? = null,
        val activeAdjectivalParticipleVariation: StandardAllKindVariation = StandardAllKindVariation(),
        val passiveAdjectiveParticipleFirst: String? = null,
        val passiveAdjectiveParticipleFirstVariation: StandardAllKindVariation = StandardAllKindVariation(),
        val passiveAdjectiveParticipleSecond: String? = null,
        val passiveAdjectiveParticipleSecondVariation: StandardAllKindVariation = StandardAllKindVariation(),
)
